# Example Security Scan Caller Workflow
#
# Security-focused scanning that BLOCKS PRs on findings
# Dynamic scans run based on what files changed
#
# For linting (Dockerfiles, shell scripts, workflows), see lint-scan-caller.yaml

name: Security

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  security-scan:
    name: Security Scan
    uses: calebsargeant/reusable-workflows/.github/workflows/security-scan.yaml@main
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    # Default settings work for most repos
    # Uncomment to enable license scanning:
    # with:
    #   enable_license_scan: true
