# Example Security Scan Caller Workflow
#
# Minimal by default - dynamic scans run based on what files changed
# Enable optional scans as needed for your project

name: Security

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Basic usage - fast, minimal
  security-scan:
    name: Security Scan
    uses: calebsargeant/reusable-workflows/.github/workflows/security-scan.yaml@main
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    # Default settings work for most repos
    # Uncomment below to enable optional scans:
    # with:
    #   enable_sast: true           # Semgrep SAST (+2 min)
    #   enable_iac_scan: true       # Checkov for Terraform/K8s (+1 min)
    #   enable_license_scan: true   # License compliance (+30s)

