# https://github.com/CalebSargeant/workflows/settings/actions
# Remember to set workflow permissions in this link

name: OpenAI Code Review

on:
  workflow_call:
    secrets:
      OPENAI_API_KEY:
        description: OpenAI API Key
jobs:
  review:
    permissions: write-all # Check permission when leave comment action failed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OpenAI PR Review
        uses: cawcaw253/ai-review-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: "English"
          MODEL: "gpt-4o-mini"