# https://github.com/CalebSargeant/workflows/settings/actions
# Remember to set workflow permissions in this link

name: Presubmit.ai

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  # Keep the original triggers if you want this workflow to run on its own too
  pull_request_target:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [created]
  # Add the workflow_call trigger to make it reusable
  workflow_call:
    # Define inputs if needed
    # inputs:
    #   llm_model:
    #     description: 'LLM model to use'
    #     default: 'gpt-4o-mini'
    #     required: false
    #     type: string
    # Define secrets that need to be passed
    secrets:
      OPENAI_API_KEY:
        description: 'OpenAI API Key'
        required: true

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "Error: OPENAI_API_KEY secret is not configured"
            exit 1
          fi
      - uses: presubmit/ai-reviewer@v0.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_MODEL: "gpt-4o-mini"