name: Terragrunt Plan/Apply

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Github Environment to deploy to (for AWS credentials)
        required: true
      working_dir:
        type: string
        description: Directory where Terragrunt commands will be executed
        required: false
        default: ./terraform
      terraform_version:
        type: string
        description: Terraform version to use
        required: false
        default: latest
      terragrunt_version:
        type: string
        description: Terragrunt version to use
        required: false
        default: latest
      aws_region:
        type: string
        description: AWS region to use
        required: false
        default: af-south-1
      enable_comments:
        type: boolean
        description: Enable PR comments for plan output
        required: false
        default: true
      auto_approve:
        type: boolean
        description: Auto approve apply (only for main/master branch)
        required: false
        default: true
      enable_infracost:
        type: boolean
        description: Enable Infracost cost estimation
        required: false
        default: true
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: 'AWS IAM role ARN to assume'
        required: true
      INFRACOST_API_KEY:
        description: 'Infracost API key'
        required: false

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ inputs.terraform_version }}
          tg_version: ${{ inputs.terragrunt_version }}
          tg_dir: ${{ inputs.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

  plan:
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws_region }}

      - name: Export AWS Environment Variables
        run: |
          echo "AWS_REGION=${{ inputs.aws_region }}" >> $GITHUB_ENV

          # Export all GitHub variables as TF_VAR_* environment variables
          echo "Exporting GitHub variables as Terraform variables"
          for var in $(env | grep -E '^(GITHUB_|CI_)' | cut -d= -f1); do
            echo "TF_VAR_${var,,}=${!var}" >> $GITHUB_ENV
          done

          # Export all secrets as TF_VAR_* environment variables (without printing values)
          echo "Exporting secrets as Terraform variables (values masked)"
          for s in $(echo '${{ toJSON(secrets) }}' | jq -r 'keys[]'); do
            if [[ "$s" != "github_token" && "$s" != "GITHUB_TOKEN" ]]; then
              echo "TF_VAR_${s,,}=***" 
              echo "TF_VAR_${s,,}=${{ secrets[format('{0}', s)] }}" >> $GITHUB_ENV
            fi
          done

      - name: Plan
        id: tg-plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ inputs.terraform_version }}
          tg_version: ${{ inputs.terragrunt_version }}
          tg_dir: ${{ inputs.working_dir }}
          tg_command: 'plan'

      - name: Post Plan Comment
        if: ${{ inputs.enable_comments == true && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terragrunt Plan 📖
            \`\`\`
            ${{ steps.tg-plan.outputs.stdout }}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

  cost:
    runs-on: ubuntu-latest
    needs: [ plan ]
    steps:
      - name: Setup Infracost
        if: ${{ inputs.enable_infracost == true && github.event_name == 'pull_request' }}
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        if: ${{ inputs.enable_infracost == true && github.event_name == 'pull_request' }}
        id: infracost
        run: |
          cd ${{ inputs.working_dir }}
          # Generate Infracost JSON directly from Terragrunt code
          infracost breakdown --path . --terraform-parse-hcl --format json --out-file infracost.json

      - name: Post Infracost Comment
        if: ${{ inputs.enable_infracost == true && github.event_name == 'pull_request' }}
        uses: infracost/actions/comment@v2
        with:
          path: ${{ inputs.working_dir }}/infracost.json
          behavior: update
          terraform-workspace: ${{ inputs.environment }}


  deploy:
    runs-on: ubuntu-latest
    needs: [ plan ]
    environment: 'prod'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws_region }}

      - name: Export AWS Environment Variables
        run: |
          echo "AWS_REGION=${{ inputs.aws_region }}" >> $GITHUB_ENV

          # Export all GitHub variables as TF_VAR_* environment variables
          echo "Exporting GitHub variables as Terraform variables"
          for var in $(env | grep -E '^(GITHUB_|CI_)' | cut -d= -f1); do
            echo "TF_VAR_${var,,}=${!var}" >> $GITHUB_ENV
          done

          # Export all secrets as TF_VAR_* environment variables (without printing values)
          echo "Exporting secrets as Terraform variables (values masked)"
          for s in $(echo '${{ toJSON(secrets) }}' | jq -r 'keys[]'); do
            if [[ "$s" != "github_token" && "$s" != "GITHUB_TOKEN" ]]; then
              echo "TF_VAR_${s,,}=***" 
              echo "TF_VAR_${s,,}=${{ secrets[format('{0}', s)] }}" >> $GITHUB_ENV
            fi
          done

      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ inputs.terraform_version }}
          tg_version: ${{ inputs.terragrunt_version }}
          tg_dir: ${{ inputs.working_dir }}
          tg_command: 'apply'
